# Generated by Django 4.2.4 on 2023-08-13 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Лидерборд',
                'verbose_name_plural': 'Лидерборды',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_status', models.BooleanField(default=False, verbose_name='Озвучка чата')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Параметры приложения',
                'verbose_name_plural': 'Параметры приложения',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Никнейм')),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Очки опыта')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Уровень')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_members', to='users.leaderboard')),
            ],
            options={
                'unique_together': {('nickname', 'leaderboard')},
            },
        ),
    ]
